services:
  - type: web
    name: nacp-registration
    env: python
    plan: free
    buildCommand: |
      buildCommand: |
  echo "Using Python 3.11.9"
  pyenv install -s 3.11.9
  pyenv global 3.11.9
  cd census_app/registration_test
  pip install --upgrade pip
  pip install -r requirements.txt

    startCommand: streamlit run census_app/registration_test/main_app.py --server.port $PORT --server.address 0.0.0.0

