services:
  - type: web
    name: agri-census
    env: python
    plan: free
    buildCommand: |
      echo "Using Python 3.11.9"
      pyenv install -s 3.11.9
      pyenv global 3.11.9
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run admin_app.py
